import test from 'node:test';import assert from 'node:assert/strict';import { readFile } from 'node:fs/promises';import { JSDOM } from 'jsdom';import { validateUpload } from '../assets/js/upload-policy.js';import { createPaymentUI } from '../assets/js/payments.js';
const html=await readFile('index.html','utf8');const script=(await readFile('assets/js/app.js','utf8')).replace(/^import .*;$/gm,'');
function setup(){
 const dom=new JSDOM(html,{url:'http://localhost:3000',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;const calls=[];
 w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.CSS={escape:s=>String(s).replace(/[\\"]/g,'\\$&')};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};
 w.createClient=()=>({auth:{getUser:async()=>({data:{user:null}})},storage:{from:()=>({uploadToSignedUrl:async()=>({error:null})})}});w.validateUpload=validateUpload;w.createPaymentUI=opts=>createPaymentUI({...opts,fetcher:async()=>({ok:false})});
 w.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);calls.push(body);return {ok:true,json:async()=>body.action==='submit'?{order_id:'559a7da0-6206-4eb0-8e53-a78d48994209',order_number:'QA-ONLY',submission_token:'mock',uploads:body.files.map((_,i)=>({path:'test/'+i,token:'mock'}))}:{order_number:'QA-ONLY'}};};
 w.eval(script);return {dom,w,d:w.document,calls};
}
function fill(d){const active=d.querySelector('.step.active');for(const n of active.querySelectorAll('input[required],textarea[required]')){if(n.type==='radio'){if(!active.querySelector(`input[name="${n.name}"]:checked`))n.checked=true;}else if(n.type==='checkbox')n.checked=true;else n.value=n.type==='number'?'5':n.type==='date'?'2027-01-01':n.type==='email'?'qa@example.invalid':n.type==='tel'?'5550100000':'Historia local de prueba';}}
test('All 12 Spanish wizard templates progress, validate, save only on request, and retain package selection',async()=>{
 const {dom,w,d}=setup();try{assert.equal(d.querySelectorAll('.tcard').length,12);assert.equal(d.querySelectorAll('main').length,1);assert(!/[\u{1F000}-\u{1FAFF}]/u.test(d.body.textContent));
  const ids=[...d.querySelectorAll('[data-t]')].map(b=>b.dataset.t);
  for(const [i,id] of ids.entries()){
   d.querySelector(`[data-t="${id}"]`).click();assert.equal(d.querySelectorAll('.step.active').length,1);d.querySelector('#next').click();assert(d.querySelector('#err').classList.contains('show'));fill(d);
   if(i===0){d.querySelector('input[required]').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.localStorage.length,0);d.querySelector('#save').click();assert.equal(w.localStorage.length,1);d.querySelector('#clearDraft').click();assert.equal(w.localStorage.length,0);}
   let count=0;while(!d.querySelector('#next').classList.contains('hidden')){fill(d);d.querySelector('#next').click();assert(++count<20);}
   fill(d);assert(d.querySelector('.step.active #review'));assert.equal(d.querySelector('input[name="Paquete"]:checked').value,'songs');assert.equal(d.querySelector('.track').getAttribute('aria-valuenow'),'100');d.querySelector('#changeTemplate').click();assert(d.querySelector('#formArea').classList.contains('hidden'));
  }
 }finally{dom.window.close();}
});
test('Local mock intake/finalize succeeds, files preserve order and captions, and checkout stays disabled',async()=>{
 const {dom,w,d,calls}=setup();try{d.querySelector('[data-t="aniversario"]').click();let count=0;while(!d.querySelector('#next').classList.contains('hidden')){fill(d);if(d.querySelector('.step.active #photoInput')){const file=new w.File(['mock-bytes'],'qa-photo.jpg',{type:'image/jpeg'});Object.defineProperty(d.querySelector('#photoInput'),'files',{value:[file]});d.querySelector('#photoInput').dispatchEvent(new w.Event('change'));const cap=d.querySelector('[data-cap]');cap.value='Solo una prueba local';cap.dispatchEvent(new w.Event('input'));assert.match(d.querySelector('#photoCount').textContent,/1 foto/);}d.querySelector('#next').click();assert(++count<20);}fill(d);await d.querySelector('#f').onsubmit({preventDefault(){}});assert.equal(calls.length,2);assert.equal(calls[0].answers['Paquete elegido'],'Canciones + letras · $20 USD');assert.equal(calls[1].file_manifest[0].role,'slideshow');assert.equal(calls[1].file_manifest[0].caption,'Solo una prueba local');assert(d.querySelector('#done').hasAttribute('open'));assert(d.querySelector('#checkoutButton').disabled);assert.equal(w.localStorage.length,0);}finally{dom.window.close();}
});
test('Pricing selection and obsolete admin setup are handled correctly',async()=>{const {dom,d}=setup();try{d.querySelector('[data-plan="slideshow"]').click();d.querySelector('[data-t="aniversario"]').click();assert.equal(d.querySelector('input[name="Paquete"]:checked').value,'slideshow');assert.equal(d.querySelector('#signupBtn'),null);d.querySelector('#footerAdmin').click();await new Promise(r=>setTimeout(r,0));assert(!d.querySelector('#adminApp').classList.contains('hidden'));assert(d.querySelector('#adminPanel').classList.contains('hidden'));}finally{dom.window.close();}});
