import test from 'node:test';import assert from 'node:assert/strict';import { readFile } from 'node:fs/promises';import { randomUUID } from 'node:crypto';import { PGlite } from '@electric-sql/pglite';
import { EdgeStore } from '../server/edge-store.js';import { EdgeIntake } from '../server/edge-intake.js';import { Payments,hashToken } from '../server/payments.js';import { NotificationWorker } from '../server/notifications.js';
import {config,body,finalFor,fixture,query,start} from './helpers/edge-fixture.js';
test('Audited v1-compatible order rows persist once; submit/finalize retries preserve capability and admin-visible fields',()=>fixture(async f=>{
 const input=body();const [a,b]=await Promise.all([f.intake.handle(input),f.intake.handle(input)]);assert.deepEqual(a,b);assert.deepEqual(await f.intake.handle({...input,idempotency_key:input.idempotency_key.toUpperCase()}),a);const [x,y]=await Promise.all([f.intake.handle(finalFor(a)),f.intake.handle(finalFor(b))]);assert.deepEqual(x,y);
 const orders=await query(f.db,'SELECT * FROM public.shia_song_orders');assert.equal(orders.length,1);assert.equal(orders[0].customer_phone,'5550100000');assert.equal(orders[0].answers.story,'Fake local story');assert.equal(orders[0].submission_token_hash,null);assert.equal((await query(f.db,'SELECT * FROM shia_edge.notifications')).length,1);assert.equal((await query(f.db,'SELECT * FROM shia_edge.payments'))[0].token_hash,hashToken(x.payment_token));
 await assert.rejects(()=>f.intake.handle({...input,package_key:'slideshow'}),{status:409});assert.equal((await query(f.db,'SELECT * FROM public.shia_song_orders')).length,1);
}));
test('Missing/unsupported files, arbitrary paths and changed finalize manifests are rejected; upload signing failure can resume',()=>fixture(async f=>{
 const input=body();input.package_key='slideshow';input.files=[{name:'fake.png',type:'image/png',size:4}];const sign=f.storage.sign;f.storage.sign=async()=>{throw new Error('fake storage outage');};await assert.rejects(()=>f.intake.handle(input));f.storage.sign=sign;const a=await f.intake.handle(input);assert.equal((await query(f.db,'SELECT * FROM public.shia_song_orders')).length,1);const m={...input.files[0],path:a.uploads[0].path,role:'slideshow',order:1,caption:'Fake caption'};
 await assert.rejects(()=>f.intake.handle({...finalFor(a),file_manifest:[m]}),{status:409});f.uploads.add(m.path);
 await assert.rejects(()=>f.intake.handle({...finalFor(a),file_manifest:[{...m,path:'other/01-fake.png'}]}),{status:400});await f.intake.handle({...finalFor(a),file_manifest:[m]});await assert.rejects(()=>f.intake.handle({...finalFor(a),file_manifest:[{...m,caption:'changed'}]}),{status:409});assert.equal((await f.intake.handle(input)).uploads[0].uploaded,true);
 await assert.rejects(()=>f.intake.handle({...body(),files:[{name:'fake.heif',type:'image/heif',size:4}]}),{status:400});
}));
test('Finalize outbox failure rolls back the existing order update and private payment state',()=>fixture(async f=>{
 const a=await f.intake.handle(body());await f.db.exec(`CREATE FUNCTION shia_edge.reject_notification() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'fake_queue_failure'; END$$; CREATE TRIGGER reject_notification BEFORE INSERT ON shia_edge.notifications FOR EACH ROW EXECUTE FUNCTION shia_edge.reject_notification();`);
 await assert.rejects(()=>f.intake.handle(finalFor(a)));assert.equal((await query(f.db,'SELECT * FROM shia_edge.requests'))[0].finalized_at,null);assert.equal((await query(f.db,'SELECT * FROM shia_edge.payments')).length,0);assert.equal((await query(f.db,'SELECT * FROM shia_edge.notifications')).length,0);
 await f.db.exec('DROP TRIGGER reject_notification ON shia_edge.notifications');assert((await f.intake.handle(finalFor(a))).payment_token);
}));
test('RPC checkout lease serializes double clicks; stored open sessions are reused',()=>fixture(async f=>{
 const {checkout}=await start(f);const create=f.stripe.checkout.sessions.create;let entered,release;const signal=new Promise(r=>entered=r);f.stripe.checkout.sessions.create=async(...args)=>{entered();await new Promise(r=>release=r);return create(...args);};const first=checkout();await signal;await assert.rejects(checkout,{status:409});release();const value=await first;assert.deepEqual(await checkout(),value);assert.equal(f.calls.length,1);
 assert.equal(f.calls[0].args.success_url,config.frontendBaseUrl+'payment-status.html');
}));
test('Stripe success/database failure retries identical durable reservation; old orphan attempts stop for reconciliation',()=>fixture(async f=>{
 const {checkout}=await start(f);f.admin.failSave=true;await assert.rejects(checkout);await checkout();assert.equal(f.calls.length,2);assert.deepEqual(f.calls[0],f.calls[1]);assert.equal(f.sessions.size,1);
 const next=await start(f);f.admin.failSave=true;await assert.rejects(next.checkout);const count=f.calls.length;await f.db.exec("UPDATE shia_edge.payments SET reserved_at=now()-interval '24 hours' WHERE reserved_attempt IS NOT NULL");await assert.rejects(next.checkout,{status:409});assert.equal(f.calls.length,count);
}));
test('Paid webhook receipts, paid alert and fulfillment commit atomically and remain deduplicated',()=>fixture(async f=>{
 const {a,checkout}=await start(f);await checkout();const s=[...f.sessions.values()][0];s.status='complete';s.payment_status='paid';const event=id=>({id,livemode:false,type:'checkout.session.completed',data:{object:{id:s.id}}});
 await f.db.exec(`CREATE FUNCTION shia_edge.reject_paid() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.kind='paid' THEN RAISE EXCEPTION 'fake_paid_queue_failure'; END IF; RETURN NEW; END$$; CREATE TRIGGER reject_paid BEFORE INSERT ON shia_edge.notifications FOR EACH ROW EXECUTE FUNCTION shia_edge.reject_paid();`);
 await assert.rejects(()=>f.payments.handleEvent(event('evt_fake')));assert.equal((await query(f.db,'SELECT * FROM shia_edge.events')).length,0);assert.equal((await query(f.db,'SELECT * FROM shia_edge.payments'))[0].payment_status,'pending');await f.db.exec('DROP TRIGGER reject_paid ON shia_edge.notifications');
 await f.payments.handleEvent(event('evt_fake'));await f.payments.handleEvent(event('evt_fake'));await f.payments.handleEvent(event('evt_fake_2'));assert.equal((await query(f.db,'SELECT * FROM shia_edge.notifications')).length,2);assert.equal((await query(f.db,'SELECT * FROM shia_edge.fulfillment')).length,1);assert.equal((await query(f.db,'SELECT * FROM shia_edge.payments'))[0].payment_status,'paid');await assert.rejects(checkout,{status:409});assert.equal((await query(f.db,'SELECT id FROM public.shia_song_orders'))[0].id,a.order_id);
}));
test('RPC notification failure retains finalized inquiry; stable keys, lease fencing and expiry recover safely',()=>fixture(async f=>{
 await start(f);let fail=true;const keys=[];const worker=new NotificationWorker({store:f.store,provider:{send:async({key})=>{keys.push(key);if(fail){fail=false;throw new Error('fake provider failure');}return 'fake-provider';}}});await worker.runOne();assert.equal((await query(f.db,'SELECT * FROM shia_edge.notifications'))[0].status,'failed');assert((await query(f.db,'SELECT * FROM shia_edge.requests'))[0].finalized_at);
 await f.db.exec('UPDATE shia_edge.notifications SET available_at=now()');await worker.runOne();assert.equal(new Set(keys).size,1);assert.equal((await query(f.db,'SELECT * FROM shia_edge.notifications'))[0].status,'sent');
 await start(f);const first=await f.store.claimNotification(randomUUID());await f.db.exec("UPDATE shia_edge.notifications SET locked_until=now()-interval '1 second' WHERE status='processing'");const second=await f.store.claimNotification(randomUUID());await f.store.finishNotification(first,{providerId:'stale'});assert.equal((await query(f.db,"SELECT * FROM shia_edge.notifications WHERE status='processing'"))[0].lease_id,second.lease_id);await f.store.finishNotification(second,{providerId:'current'});
}));
test('Service-only RPC grants, private state isolation and narrowly scoped TRUNCATE revocation preserve inventory/admin grants',()=>fixture(async f=>{
 const before=await query(f.db,"SELECT has_table_privilege('authenticated','public.inventory_probe','TRUNCATE') AS allowed");assert.equal(before[0].allowed,true);await f.db.exec(await readFile('supabase/migrations/202610030002_shia_revoke_truncate.sql','utf8'));
 const checks=await query(f.db,"SELECT has_table_privilege('authenticated','public.shia_song_orders','TRUNCATE') AS truncate,has_table_privilege('authenticated','public.shia_song_orders','UPDATE') AS update,has_table_privilege('authenticated','public.inventory_probe','TRUNCATE') AS inventory");assert.deepEqual(checks[0],{truncate:false,update:true,inventory:true});
 for(const role of ['anon','authenticated']){await f.db.exec('SET ROLE '+role);await assert.rejects(()=>f.db.query('SELECT public.shia_edge_rate_limit($1)',['intake']),/permission denied/);await assert.rejects(()=>f.db.query('SELECT * FROM shia_edge.requests'),/permission denied/);await f.db.exec('RESET ROLE');}
 await f.db.exec('SET ROLE service_role');assert.equal((await f.db.query('SELECT public.shia_edge_rate_limit($1) AS allowed',['intake'])).rows[0].allowed,true);await assert.rejects(()=>f.db.query('SELECT * FROM shia_edge.payments'),/permission denied/);await f.db.exec('RESET ROLE');
}));
test('Existing membership still governs SHIA order/admin access; payment status is member-only and read-only',()=>fixture(async f=>{
 const {a}=await start(f);await f.db.exec('SET ROLE authenticated');await assert.rejects(()=>f.db.query('SELECT public.shia_edge_admin_payment_status($1)',[[a.order_id]]),/shia_forbidden/);assert.equal((await f.db.query('SELECT id FROM public.shia_song_orders')).rows.length,0);await f.db.exec('RESET ROLE');
 const adminId=randomUUID();await f.db.query('INSERT INTO auth.users(id) VALUES($1)',[adminId]);await f.db.query('INSERT INTO public.shia_admins(user_id) VALUES($1)',[adminId]);await f.db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[adminId]);await f.db.exec('SET ROLE authenticated');
 assert.equal((await f.db.query('SELECT id FROM public.shia_song_orders')).rows.length,1);const state=(await f.db.query('SELECT public.shia_edge_admin_payment_status($1) AS state',[[a.order_id]])).rows[0].state;assert.deepEqual(state,[{order_id:a.order_id,payment_status:'pending',paid_at:null}]);assert(!JSON.stringify(state).includes('token'));
 await f.db.query("UPDATE public.shia_song_orders SET status='reviewing' WHERE id=$1",[a.order_id]);await assert.rejects(()=>f.db.query("UPDATE shia_edge.payments SET payment_status='paid'"),/permission denied/);await f.db.exec('RESET ROLE');assert.equal((await query(f.db,'SELECT status FROM public.shia_song_orders'))[0].status,'reviewing');
}));
test('Additive migrations do not backfill/replay legacy inquiries, consume their tokens, alter inventory or drop existing admin policies',async()=>{
 const db=new PGlite();try{await db.exec(await readFile('tests/fixtures/shia-v1.sql','utf8'));await db.exec("INSERT INTO public.shia_song_orders(customer_name,customer_email,customer_phone,submission_token_hash) VALUES('Fake legacy','legacy@example.invalid','5550100000','fake-original-hash'); INSERT INTO public.inventory_probe VALUES(1,'fake untouched inventory');");
 const orders=await query(db,'SELECT * FROM public.shia_song_orders'),inventory=await query(db,'SELECT * FROM public.inventory_probe'),policies=await query(db,"SELECT policyname,cmd,qual,with_check FROM pg_policies WHERE tablename IN ('shia_song_orders','shia_admins') ORDER BY policyname");await db.exec(await readFile('supabase/migrations/202610030001_shia_edge.sql','utf8'));await db.exec(await readFile('supabase/migrations/202610030002_shia_revoke_truncate.sql','utf8'));
 assert.deepEqual(await query(db,'SELECT * FROM public.shia_song_orders'),orders);assert.deepEqual(await query(db,'SELECT * FROM public.inventory_probe'),inventory);assert.deepEqual(await query(db,"SELECT policyname,cmd,qual,with_check FROM pg_policies WHERE tablename IN ('shia_song_orders','shia_admins') ORDER BY policyname"),policies);assert.equal((await query(db,'SELECT * FROM shia_edge.notifications')).length,0);assert.equal((await query(db,'SELECT * FROM shia_edge.requests')).length,0);
 }finally{await db.close();}
});
test('A paid webhook racing a leased checkout prevents another session reservation',()=>fixture(async f=>{
 const {checkout}=await start(f);await checkout();const session=[...f.sessions.values()][0];session.status='expired';const retrievePrice=f.stripe.prices.retrieve;
 f.stripe.prices.retrieve=async id=>{session.status='complete';session.payment_status='paid';await f.payments.handleEvent({id:'evt_racing_paid',livemode:false,type:'checkout.session.completed',data:{object:{id:session.id}}});return retrievePrice(id);};
 await assert.rejects(checkout,{status:409});assert.equal(f.calls.length,1);assert.equal((await query(f.db,'SELECT * FROM shia_edge.payments'))[0].payment_status,'paid');
}));
test('Expired checkout leases fence stale saves/releases without losing the persisted attempt',()=>fixture(async f=>{
 const {a,final}=await start(f);const first=randomUUID(),second=randomUUID();const args={p_order_id:a.order_id,p_token_hash:hashToken(final.payment_token),p_package_key:'songs'};
 await f.store.rpc('payment_claim',{...args,p_lease_id:first});await f.store.rpc('payment_reserve',{p_order_id:a.order_id,p_lease_id:first,p_attempt:1,p_request_hash:'a'.repeat(64)});await f.db.exec("UPDATE shia_edge.payments SET locked_until=now()-interval '1 second'");await f.store.rpc('payment_claim',{...args,p_lease_id:second});
 await assert.rejects(()=>f.store.rpc('payment_save',{p_order_id:a.order_id,p_lease_id:first,p_session_id:'cs_stale',p_attempt:1,p_price_id:'price_songs',p_amount:2000,p_currency:'usd'}),{status:409});await f.store.rpc('payment_release',{p_order_id:a.order_id,p_lease_id:first});const row=(await query(f.db,'SELECT * FROM shia_edge.payments'))[0];assert.equal(row.lease_id,second);assert.equal(row.reserved_attempt,1);assert.equal((await query(f.db,'SELECT * FROM shia_edge.sessions')).length,0);
}));

test('RPC proof and package checks fail closed on NULL independently of the HTTP validator',()=>fixture(async f=>{
 const {a}=await start(f);await assert.rejects(()=>f.store.rpc('finalize',{p_order_id:a.order_id,p_token_hash:null,p_manifest:[],p_payment_hash:null}),{status:403});await assert.rejects(()=>f.store.rpc('payment_claim',{p_order_id:a.order_id,p_token_hash:null,p_package_key:'songs',p_lease_id:randomUUID()}),{status:403});
}));

test('Stripe references/idempotency use the durable canonical UUID even when a caller changes UUID casing',()=>fixture(async f=>{
 const {a,final}=await start(f);await f.payments.checkout({orderId:a.order_id.toUpperCase(),paymentToken:final.payment_token,packageKey:'songs'});assert.equal(f.calls[0].args.client_reference_id,a.order_id);assert.equal(f.calls[0].args.metadata.shia_order_id,a.order_id);assert(f.calls[0].options.idempotencyKey.includes(a.order_id));
 const session=[...f.sessions.values()][0];session.status='complete';session.payment_status='paid';await f.payments.handleEvent({id:'evt_canonical',livemode:false,type:'checkout.session.completed',data:{object:{id:session.id}}});assert.equal((await query(f.db,'SELECT * FROM shia_edge.payments'))[0].payment_status,'paid');
}));
