import { chromium } from 'playwright';import { createServer } from 'node:http';import assert from 'node:assert/strict';import { readFile,mkdir,writeFile } from 'node:fs/promises';import Stripe from 'stripe';
import { createApp,readBody } from '../server/app.js';import { readConfig } from '../server/catalog.js';import { createEdgeHandler } from '../server/edge-http.js';import { NotificationWorker } from '../server/notifications.js';import {fixture,config,query} from './helpers/edge-fixture.js';
await fixture(async f=>{
 let alerts=0;const worker=new NotificationWorker({store:f.store,provider:{send:async()=>{alerts++;return 'fake-provider-accepted';}}});const signing=new Stripe('sk_test_fake_only'),secret='whsec_fake_only';config.workerSecret='fake-edge-worker-secret-32-characters';
 const handler=createEdgeHandler({config,payments:f.payments,intake:f.intake,worker,rateLimit:async request=>{assert(await f.store.rpc('rate_limit',{p_scope:new URL(request.url).pathname.endsWith('/checkout')?'checkout':'intake'}));},verifyWebhook:(raw,signature)=>signing.webhooks.constructEventAsync(raw,signature,secret,undefined,Stripe.createSubtleCryptoProvider()),paths:{api:'/functions/v1/shia-song-payments',intake:'/functions/v1/shia-order-intake-v2',webhook:'/functions/v1/shia-stripe-webhook',worker:'/functions/v1/shia-song-notifications'}});
 const edge=createServer(async(req,res)=>{try{const body=['GET','HEAD'].includes(req.method)?undefined:await readBody(req,1024*1024);const request=new Request(`http://localhost${req.url}`,{method:req.method,headers:req.headers,body});const response=await handler(request);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch{res.writeHead(500);res.end('{}');}});await new Promise(r=>edge.listen(0,'127.0.0.1',r));const edgeLocal=`http://127.0.0.1:${edge.address().port}`,edgePublic='https://edge.example.invalid';
 const pageConfig=readConfig({});pageConfig.storageOrigin=edgePublic;const staticApp=createApp({config:pageConfig,payments:{}});const html=(await readFile('index.html','utf8')).replace('name="shia-intake-endpoint" content=""',`name="shia-intake-endpoint" content="${edgePublic}/functions/v1/shia-order-intake-v2"`).replace('name="shia-payment-api" content=""',`name="shia-payment-api" content="${edgePublic}/functions/v1/shia-song-payments/"`);
 const pages=createServer((req,res)=>{if(req.url==='/Shia-songs/'||req.url==='/Shia-songs/index.html'){res.writeHead(200,{'Content-Type':'text/html'});return res.end(html);}req.url=req.url.replace(/^\/Shia-songs\//,'/');return staticApp(req,res);});await new Promise(r=>pages.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${pages.address().port}`;pageConfig.origin=origin;config.origin=origin;config.frontendBaseUrl=origin+'/Shia-songs/';
 f.storage.sign=async path=>({token:'fake-token',upload_url:edgePublic+'/fake-upload/'+path});
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext({reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let lostSubmit=true,lostFinalize=true,submits=0,finalizes=0,preflights=0;
 await context.route('**/*',async route=>{
  const req=route.request(),url=new URL(req.url());if(url.origin===origin)return route.continue();if(url.hostname==='checkout.stripe.com')return route.fulfill({body:'Fake hosted checkout only.'});if(url.origin!==edgePublic)return route.abort();
  if(req.method()==='OPTIONS')preflights++;
  if(url.pathname.startsWith('/fake-upload/')){if(req.method()==='PUT')f.uploads.add(url.pathname.slice('/fake-upload/'.length));return route.fulfill({status:200,headers:{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'PUT,OPTIONS','Access-Control-Allow-Headers':'content-type'},body:'{}'});}
  const response=await fetch(edgeLocal+url.pathname,{method:req.method(),headers:req.headers(),body:['GET','HEAD'].includes(req.method())?undefined:req.postDataBuffer()});const responseBody=Buffer.from(await response.arrayBuffer());
  if(url.pathname.endsWith('/shia-order-intake-v2')&&req.method()==='POST'){const action=req.postDataJSON().action;if(action==='submit'){submits++;if(lostSubmit){lostSubmit=false;return route.abort();}}else{finalizes++;if(lostFinalize){lostFinalize=false;return route.abort();}}}
  return route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:responseBody});
 });
 async function fill(){const active=page.locator('.step.active');for(const el of await active.locator('input[required]:not([type=radio]):not([type=checkbox]),textarea[required]').all()){const type=await el.getAttribute('type');await el.fill(({number:'5',date:'2027-01-01',email:'fake@example.invalid',tel:'5550100000'})[type]||'Fake local Edge story');}await active.locator('input[type=radio][required]').evaluateAll(items=>{for(const name of new Set(items.map(i=>i.name)))items.find(i=>i.name===name).checked=true;});for(const el of await active.locator('input[type=checkbox][required]').all())await el.check();}
 const results=[];
 try{
  for(const lang of ['en','es']){
   await page.goto(config.frontendBaseUrl);await page.locator(`[data-language=${lang}]`).first().click();await page.locator('[data-t=personalizada]').click();while(await page.locator('#next').isVisible()){await fill();if(lang==='es'&&await page.locator('#photoInput').isVisible()){const buffer=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aRFAAAAAASUVORK5CYII=','base64');await page.locator('#photoInput').setInputFiles({name:'fake.png',mimeType:'image/png',buffer});await page.locator('[data-cap="0"]').fill('Fake Edge caption');}await page.locator('#next').click();}await fill();if(lang==='es')await page.locator('input[name=Paquete][value=slideshow]').locator('..').locator('span').first().click();
   await page.locator('#submit').click();if(lang==='en'){await page.waitForFunction(()=>!document.querySelector('#f').classList.contains('submitting'));await page.locator('#submit').click();await page.waitForFunction(()=>!document.querySelector('#f').classList.contains('submitting'));await page.locator('#submit').click();}await page.locator('#done[open]').waitFor();assert(await page.locator('#checkoutButton').isEnabled());await page.screenshot({path:`/tmp/shia-edge-${lang}.png`});await page.locator('#checkoutButton').click();await page.waitForURL('https://checkout.stripe.com/**');
   const session=[...f.sessions.values()].at(-1);assert.equal(session.amount_total,lang==='en'?2000:5000);session.status='complete';session.payment_status='paid';const raw=JSON.stringify({id:'evt_fake_'+lang,livemode:false,type:'checkout.session.completed',data:{object:{id:session.id}}}),signature=signing.webhooks.generateTestHeaderString({payload:raw,secret});for(let i=0;i<2;i++)assert.equal((await fetch(edgeLocal+'/functions/v1/shia-stripe-webhook',{method:'POST',headers:{'stripe-signature':signature},body:raw})).status,200);results.push({language:lang,amount:session.amount_total,localOrderSaved:true,mockCheckoutOpened:true,verifiedLocalSignedWebhook:true});
  }
  const orders=await query(f.db,'SELECT * FROM public.shia_song_orders');assert.equal(orders.length,2);assert.equal(orders[1].file_manifest[0].caption,'Fake Edge caption');assert.equal((await query(f.db,"SELECT * FROM shia_edge.payments WHERE payment_status='paid'")).length,2);assert.equal((await query(f.db,'SELECT * FROM shia_edge.notifications')).length,4);assert.equal(f.sessions.size,2);
  while((await fetch(edgeLocal+'/functions/v1/shia-song-notifications',{method:'POST',headers:{authorization:`Bearer ${config.workerSecret}`}})).ok){if((await query(f.db,"SELECT * FROM shia_edge.notifications WHERE status='sent'")).length===4)break;}assert.equal(alerts,4);assert.deepEqual(errors,[]);
  await mkdir('artifacts',{recursive:true});const report={results,submits,finalizes,preflights,localOrders:2,mockSessions:2,mockAcceptedAlerts:alerts,realExternalRequests:0,errors};await writeFile('artifacts/edge-browser-report.json',JSON.stringify(report,null,2));console.log('Pages-path/Edge/RPC browser integration passed in English and Spanish; no real external requests.');
 }finally{await browser.close();await new Promise(r=>pages.close(r));await new Promise(r=>edge.close(r));}
});
