import test from 'node:test';import assert from 'node:assert/strict';import { JSDOM } from 'jsdom';import { buildSync } from 'esbuild';
const source=buildSync({entryPoints:['assets/js/payments.js'],bundle:true,write:false,format:'iife',globalName:'PaymentUI'}).outputFiles[0].text;
const order={orderId:'559a7da0-6206-4eb0-8e53-a78d48994209',token:'fake-capability',packageKey:'songs'};
function fixture(options={}){const dom=new JSDOM('<button id="button"></button><div id="panel" class="hidden"></div><p id="note"></p>',{url:'https://pages.example.invalid/Shia-songs/',runScripts:'outside-only'});dom.window.eval(source);const d=dom.window.document;const button=d.querySelector('#button'),panel=d.querySelector('#panel'),note=d.querySelector('#note');return {dom,button,note,ui:dom.window.PaymentUI.createPaymentUI({button,panel,note,...options})};}
test('Static Pages can use an explicitly configured HTTPS edge API without leaking capability into URLs; double clicks start once',async()=>{
 const calls=[],redirects=[];let release;const f=fixture({apiBase:'https://edge.example.invalid/functions/v1/shia-payments/',navigate:url=>redirects.push(url),fetcher:async(url,opts)=>{calls.push({url,opts});if(url.endsWith('payment-config'))return {ok:true,json:async()=>({enabled:true,packages:[{key:'songs'}]})};await new Promise(r=>release=r);return {ok:true,json:async()=>({url:'https://checkout.stripe.com/c/pay/fake-only'})};}});
 try{await f.ui.setOrder(order);assert.equal(f.button.disabled,false);f.button.click();f.button.click();assert.equal(calls.length,2);assert.equal(f.button.disabled,true);release();await new Promise(r=>setTimeout(r,0));assert.equal(redirects.length,1);assert.equal(calls[0].url,'https://edge.example.invalid/functions/v1/shia-payments/payment-config');assert.equal(calls[1].url,'https://edge.example.invalid/functions/v1/shia-payments/checkout');assert.deepEqual(JSON.parse(calls[1].opts.body),{orderId:order.orderId,paymentToken:order.token,packageKey:order.packageKey});assert(calls.every(c=>!c.url.includes(order.token)));}finally{f.dom.window.close();}
});
test('Unsafe or malformed configured API bases fail closed without a request',async()=>{
 for(const apiBase of ['http://edge.example.invalid/api/','https://user:password@edge.example.invalid/api/','https://edge.example.invalid/api/?token=fake','https://edge.example.invalid/api','javascript:fake']){
  let calls=0;const f=fixture({apiBase,fetcher:async()=>{calls++;}});try{await f.ui.setOrder(order);assert.equal(f.button.disabled,true);assert.equal(calls,0);}finally{f.dom.window.close();}
 }
});
test('Default static checkout remains disabled without the trusted finalize capability',async()=>{let calls=0;const f=fixture({fetcher:async()=>{calls++;}});try{await f.ui.setOrder({...order,token:undefined});assert.equal(f.button.disabled,true);assert.equal(calls,0);}finally{f.dom.window.close();}});
test('A stale payment-config response cannot enable checkout for a newer tokenless inquiry',async()=>{let release;const f=fixture({fetcher:async()=>{await new Promise(r=>release=r);return {ok:true,json:async()=>({enabled:true,packages:[{key:'songs'}]})};}});try{const first=f.ui.setOrder(order);await f.ui.setOrder({...order,token:undefined});release();await first;assert.equal(f.button.disabled,true);}finally{f.dom.window.close();}});
