import test from 'node:test';
import assert from 'node:assert/strict';
import Stripe from 'stripe';
import { createServer } from 'node:http';
import { readConfig,publicConfig } from '../server/catalog.js';
import { Payments,paymentCapability,hashToken } from '../server/payments.js';
import { createApp } from '../server/app.js';
const id='559a7da0-6206-4eb0-8e53-a78d48994209';
const config={enabled:true,origin:'http://localhost:3000',priceIds:{songs:'price_songs',slideshow:'price_slideshow'},tokenSecret:'mock-token-secret-not-a-credential',bridgeSecret:'mock-intake-secret-not-a-credential',webhookSecret:'whsec_unit_test_only'};
class MemoryStore{
  orders=new Map();sessions=new Map();events=new Set();jobs=new Map();lock=Promise.resolve();
  async provision({orderId,packageKey,tokenHash}){if(this.orders.has(orderId)){assert.equal(this.orders.get(orderId).package_key,packageKey);return;}this.orders.set(orderId,{order_id:orderId,package_key:packageKey,token_hash:tokenHash,token_expires_at:new Date(Date.now()+86400000).toISOString(),payment_status:'pending',checkout_attempt:0});}
  async withOrder(orderId,fn){const work=this.lock.then(async()=>{const original=this.orders.get(orderId),order=original?structuredClone(original):undefined;let record;const result=await fn(order,{saveSession:async(v)=>{if(this.failSave){this.failSave=false;throw new Error('mock commit failure');}record=v;}});if(record){this.sessions.set(record.sessionId,{session_id:record.sessionId,order_id:orderId,package_key:order.package_key,price_id:record.priceId,amount:record.amount,currency:record.currency});Object.assign(original,{checkout_session_id:record.sessionId,checkout_attempt:record.attempt,integration_identifier:record.integrationIdentifier});}return result;});this.lock=work.catch(()=>{});return work;}
  async session(sessionId){return this.sessions.get(sessionId);}
  async applyEvent(v){if(this.events.has(v.eventId))return;this.events.add(v.eventId);const o=this.orders.get(v.orderId);if(v.paid){o.payment_status='paid';if(!this.jobs.has(v.orderId))this.jobs.set(v.orderId,{sessionId:v.sessionId});}else if(o.payment_status!=='paid'&&(v.failed||v.expired)){o.payment_status=v.failed?'failed':'expired';}}
}
function fixture(packageKey='songs'){
  const store=new MemoryStore(),sessions=new Map(),calls=[];let seq=0;
  const stripe={prices:{retrieve:async(priceId)=>({id:priceId,active:true,livemode:false,type:'one_time',unit_amount:priceId==='price_songs'?2000:5000,currency:'usd'})},checkout:{sessions:{create:async(args,options)=>{calls.push({args,options});const prior=[...sessions.values()].find(x=>x.key===options.idempotencyKey);if(prior)return prior;const session={id:'cs_test_'+(++seq),url:'https://checkout.stripe.com/c/pay/'+seq,livemode:false,mode:'payment',status:'open',payment_status:'unpaid',client_reference_id:args.client_reference_id,metadata:args.metadata,amount_total:packageKey==='songs'?2000:5000,currency:'usd',key:options.idempotencyKey};sessions.set(session.id,session);return session;},retrieve:async(sessionId)=>{if(!sessions.has(sessionId))throw new Error('Not found');return sessions.get(sessionId);},listLineItems:async()=>({has_more:false,data:[{price:{id:config.priceIds[packageKey]},quantity:1}]})}}};
  const payments=new Payments({stripe,store,config});return {payments,store,stripe,sessions,calls,token:paymentCapability(id,packageKey,config.tokenSecret),packageKey};
}
async function setup(f){await f.payments.provision({orderId:id,packageKey:f.packageKey});}
const checkout=f=>f.payments.checkout({orderId:id,paymentToken:f.token,packageKey:f.packageKey});
const event=(sessionId,type='checkout.session.completed',eventId='evt_1')=>({id:eventId,type,livemode:false,data:{object:{id:sessionId}}});
test('Default config is closed; public config exposes no keys or tokens',()=>{const c=readConfig({});assert.equal(c.enabled,false);assert.equal(readConfig({CHECKOUT_ENABLED:'true',STRIPE_API_KEY:'rk_live_refused'}).enabled,false);const json=JSON.stringify(publicConfig(c));assert(!json.includes('secret'));assert(!json.includes('apiKey'));assert.equal(publicConfig(c).packages[0].amount,2000);assert.equal(publicConfig(c).packages[1].amount,5000);});
test('Provision is deterministic; invalid order IDs and packages are refused',async()=>{const f=fixture();await setup(f);assert.equal((await f.payments.provision({orderId:id,packageKey:'songs'})).paymentToken,f.token);await assert.rejects(()=>f.payments.provision({orderId:'123',packageKey:'songs'}));await assert.rejects(()=>f.payments.provision({orderId:id,packageKey:'other'}));});
test('Checkout requires the order-bound token and matching package',async()=>{const f=fixture();await setup(f);await assert.rejects(()=>f.payments.checkout({orderId:id,paymentToken:'tampered',packageKey:'songs'}),{status:403});await assert.rejects(()=>f.payments.checkout({orderId:id,paymentToken:f.token,packageKey:'slideshow'}),{status:403});f.store.orders.get(id).token_expires_at='2000-01-01';await assert.rejects(()=>checkout(f),{status:403});assert.equal(f.calls.length,0);});
test('Browser amounts/price IDs are ignored and trusted server Price ID is used',async()=>{const f=fixture();await setup(f);await f.payments.checkout({orderId:id,paymentToken:f.token,packageKey:'songs',amount:1,priceId:'price_attack'});const call=f.calls[0];assert.deepEqual(call.args.line_items,[{price:'price_songs',quantity:1}]);assert.equal(call.args.mode,'payment');assert(!('payment_method_types' in call.args));assert(!('automatic_tax' in call.args));assert.match(call.args.integration_identifier,/^shia-songs-[a-z]{8}$/);assert.equal(call.args.consent_collection.terms_of_service,'required');});
test('Wrong currency, wrong amount, inactive or live Stripe prices are refused',async()=>{for(const override of [{currency:'eur'},{unit_amount:1},{active:false},{livemode:true},{type:'recurring'}]){const f=fixture();await setup(f);f.stripe.prices.retrieve=async()=>({active:true,livemode:false,type:'one_time',unit_amount:2000,currency:'usd',...override});await assert.rejects(()=>checkout(f),{status:503});assert.equal(f.calls.length,0);}});
test('Concurrent checkout reuses the durable open session',async()=>{const f=fixture();await setup(f);const values=await Promise.all([checkout(f),checkout(f),checkout(f)]);assert.equal(f.calls.length,1);assert.equal(values[0].url,values[2].url);});
test('Stripe-success / database-failure retry retains identical idempotency body',async()=>{const f=fixture();await setup(f);f.store.failSave=true;await assert.rejects(()=>checkout(f));await checkout(f);assert.equal(f.calls.length,2);assert.deepEqual(f.calls[0],f.calls[1]);assert.equal(f.sessions.size,1);});
test('A completed unpaid session cannot cause a second checkout',async()=>{const f=fixture();await setup(f);await checkout(f);[...f.sessions.values()][0].status='complete';await assert.rejects(()=>checkout(f),{status:409});assert.equal(f.calls.length,1);});
test('Expired checkout creates a new durable attempt',async()=>{const f=fixture();await setup(f);await checkout(f);[...f.sessions.values()][0].status='expired';await checkout(f);assert.equal(f.calls.length,2);assert.notEqual(f.calls[0].options.idempotencyKey,f.calls[1].options.idempotencyKey);});
test('Completed unpaid event does not fulfill; async success fulfills once',async()=>{const f=fixture();await setup(f);await checkout(f);const session=[...f.sessions.values()][0];session.status='complete';await f.payments.handleEvent(event(session.id));assert.equal(f.store.jobs.size,0);session.payment_status='paid';await f.payments.handleEvent(event(session.id,'checkout.session.async_payment_succeeded','evt_2'));await f.payments.handleEvent(event(session.id,'checkout.session.async_payment_succeeded','evt_2'));await f.payments.handleEvent(event(session.id,'checkout.session.completed','evt_3'));assert.equal(f.store.jobs.size,1);assert.equal(f.store.orders.get(id).payment_status,'paid');await assert.rejects(()=>checkout(f),{status:409});});
test('Failed or expired events never overwrite a confirmed paid order',async()=>{const f=fixture();await setup(f);await checkout(f);const s=[...f.sessions.values()][0];s.status='complete';s.payment_status='paid';await f.payments.handleEvent(event(s.id));s.payment_status='unpaid';await f.payments.handleEvent(event(s.id,'checkout.session.async_payment_failed','evt_fail'));assert.equal(f.store.orders.get(id).payment_status,'paid');assert.equal(f.store.jobs.size,1);});
test('Tampered, unknown, and live sessions never fulfill',async()=>{const f=fixture();await setup(f);await checkout(f);const s=[...f.sessions.values()][0];s.status='complete';s.payment_status='paid';s.metadata.package_key='slideshow';await assert.rejects(()=>f.payments.handleEvent(event(s.id)),{status:400});s.metadata.package_key='songs';s.amount_total=1;await assert.rejects(()=>f.payments.handleEvent(event(s.id)),{status:400});assert.equal(f.store.jobs.size,0);await assert.rejects(()=>f.payments.handleEvent({...event(s.id),livemode:true}),{status:400});});
test('Mismatched line items are rejected even if session totals match',async()=>{const f=fixture();await setup(f);await checkout(f);const s=[...f.sessions.values()][0];s.status='complete';s.payment_status='paid';f.stripe.checkout.sessions.listLineItems=async()=>({has_more:false,data:[{price:{id:'price_other'},quantity:1}]});await assert.rejects(()=>f.payments.handleEvent(event(s.id)),{status:400});assert.equal(f.store.jobs.size,0);});
test('Slideshow uses the confirmed $50 one-time bundle',async()=>{const f=fixture('slideshow');await setup(f);await checkout(f);assert.equal(f.calls[0].args.line_items[0].price,'price_slideshow');});
test('HTTP verifies raw webhook bytes/signature and enforces origin/private bridge',async()=>{
 const f=fixture();await setup(f);await checkout(f);const s=[...f.sessions.values()][0];s.status='complete';s.payment_status='paid';const sdk=new Stripe('sk_test_mock_only');f.stripe.webhooks=sdk.webhooks;
 const server=createServer(createApp({config,payments:f.payments,stripe:f.stripe}));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 try{
  let res=await fetch(base+'/api/checkout',{method:'POST',headers:{Origin:'https://evil.invalid','Content-Type':'application/json'},body:'{}'});assert.equal(res.status,403);
  res=await fetch(base+'/internal/payment-orders',{method:'POST',body:'{}'});assert.equal(res.status,401);
  const payload=JSON.stringify(event(s.id));const signature=sdk.webhooks.generateTestHeaderString({payload,secret:config.webhookSecret});
  res=await fetch(base+'/api/stripe-webhook',{method:'POST',headers:{'stripe-signature':signature},body:payload});assert.equal(res.status,200);assert.equal(f.store.jobs.size,1);
  res=await fetch(base+'/api/stripe-webhook',{method:'POST',headers:{'stripe-signature':signature},body:payload+' '});assert.equal(res.status,400);
  res=await fetch(base+'/.env');assert.equal(res.status,404);res=await fetch(base+'/server/schema.sql');assert.equal(res.status,404);res=await fetch(base+'/');assert.equal(res.status,200);assert.match(res.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);
 }finally{await new Promise(r=>server.close(r));}
});
