import assert from 'node:assert/strict';import { readFile } from 'node:fs/promises';import { randomUUID } from 'node:crypto';import { PGlite } from '@electric-sql/pglite';
import { EdgeStore } from '../../server/edge-store.js';import { EdgeIntake } from '../../server/edge-intake.js';import { Payments,hashToken } from '../../server/payments.js';import { NotificationWorker } from '../../server/notifications.js';
export const config={enabled:true,origin:'https://pages.example.invalid',frontendBaseUrl:'https://pages.example.invalid/Shia-songs/',tokenSecret:'fake-payment-capability-secret-32-chars',intakeSecret:'fake-intake-capability-secret-32-chars',priceIds:{songs:'price_songs',slideshow:'price_slideshow'}};
const signatures={submit:['p_request_hash','p_payload_hash','p_order_id','p_token_hash','p_order','p_files','p_package_key'],request:['p_order_id','p_token_hash'],finalize:['p_order_id','p_token_hash','p_manifest','p_payment_hash'],payment_claim:['p_order_id','p_token_hash','p_package_key','p_lease_id'],payment_reserve:['p_order_id','p_lease_id','p_attempt','p_request_hash'],payment_save:['p_order_id','p_lease_id','p_session_id','p_attempt','p_price_id','p_amount','p_currency'],payment_release:['p_order_id','p_lease_id'],session:['p_session_id'],event:['p_event_id','p_event_type','p_session_id','p_order_id','p_paid','p_failed','p_expired'],notification_claim:['p_lease_id'],notification_finish:['p_id','p_lease_id','p_status','p_provider_id','p_error','p_delay'],rate_limit:['p_scope']};
export const body=()=>({action:'submit',idempotency_key:randomUUID(),package_key:'songs',customer_name:'Fake customer',customer_email:'fake@example.invalid',customer_phone:'5550100000',answers:{'Tipo de canción':'Personalizada',story:'Fake local story'},files:[]});
export const finalFor=a=>({action:'finalize',order_id:a.order_id,submission_token:a.submission_token,file_manifest:[]});
export async function fixture(fn){
 const db=new PGlite();await db.exec(await readFile('tests/fixtures/shia-v1.sql','utf8'));await db.exec(await readFile('supabase/migrations/202610030001_shia_edge.sql','utf8'));
 const admin={failSave:false,rpc:async(name,args)=>{if(admin.failSave&&name==='shia_edge_payment_save'){admin.failSave=false;return {error:{message:'fake_save_failure'}};}const names=signatures[name.replace('shia_edge_','')];assert(names);try{const values=names.map(n=>['p_order','p_files','p_manifest'].includes(n)?JSON.stringify(args[n]):args[n]);const result=await db.query(`SELECT public.${name}(${names.map((_,i)=>'$'+(i+1)).join(',')}) AS result`,values);return {data:result.rows[0].result,error:null};}catch(error){return {data:null,error:{message:error.message,code:error.code}};}}};
 const store=new EdgeStore(admin),uploads=new Set(),storage={sign:async path=>({token:'fake-upload-token',upload_url:'https://storage.example.invalid/'+path}),verify:async f=>uploads.has(f.path)};const intake=new EdgeIntake({store,storage,config});
 let seq=0;const sessions=new Map(),calls=[];const stripe={prices:{retrieve:async id=>({livemode:false,active:true,type:'one_time',unit_amount:id==='price_songs'?2000:5000,currency:'usd'})},checkout:{sessions:{create:async(args,options)=>{calls.push({args,options});const prior=[...sessions.values()].find(s=>s.key===options.idempotencyKey);if(prior)return prior;const s={id:'cs_fake_'+(++seq),livemode:false,url:'https://checkout.stripe.com/c/pay/fake-'+seq,status:'open',payment_status:'unpaid',mode:'payment',amount_total:args.line_items[0].price==='price_songs'?2000:5000,currency:'usd',client_reference_id:args.client_reference_id,metadata:args.metadata,key:options.idempotencyKey,price:args.line_items[0].price};sessions.set(s.id,s);return s;},retrieve:async id=>sessions.get(id),listLineItems:async id=>({has_more:false,data:[{price:{id:sessions.get(id).price},quantity:1}]})}}};const payments=new Payments({config,store,stripe});
 try{await fn({db,admin,store,intake,uploads,storage,payments,stripe,calls,sessions});}finally{await db.close();}
}
export const query=async(db,sql)=>(await db.query(sql)).rows;
export const start=async f=>{const a=await f.intake.handle(body());const final=await f.intake.handle(finalFor(a));return {a,final,checkout:()=>f.payments.checkout({orderId:a.order_id,paymentToken:final.payment_token,packageKey:'songs'})};};
